### PR TITLE
Better solution and unset HTTPS header

### PR DESCRIPTION
**Pull request by tomsommer**

### CODE REVIEW

**Comment by VlooMan** [comment]
Are you also getting this error upon activation?

<blockquote>Parse error: syntax error, unexpected T_BOOLEAN_OR in aaa-ishyoboy-google-chrome-44-ssl-fix.php on line 22</blockquote>

**Comment by tomsommer** [comment]
Fixed.

**Comment by tomsommer** [comment]
I did some research, and boiled it down to one line. So here it is, if you plan on merging it :)

**Comment by VlooMan** [comment]
Hmm, based on many replies and mainly the WooCommerce problem I don't think this is a good solution. WooCommerce used to read the "HTTP_HTTPS" property which then caused troubles and they fixed this in their latest version to resolve the problems.

**Comment by tomsommer** [comment]
Why is it not a good solution?

The problem exist because HTTP_HTTPS exists, this removes it.

**Comment by VlooMan** [comment]
Did some more reading and I agree this is a very nice check! However, the simple unsetting did not solve the problem on some of our sites so I would definitely turn the HTTPS off. Please set the $_SERVER['HTTPS'] = false; or to "off".

The reason is the is_ssl() function:

function is_ssl() {
    if ( isset($_SERVER['HTTPS']) ) {
        if ( 'on' == strtolower($_SERVER['HTTPS']) )
            return true;
        if ( '1' == $_SERVER['HTTPS'] )
            return true;
    } elseif ( isset($_SERVER['SERVER_PORT']) && ( '443' == $_SERVER['SERVER_PORT'] ) ) {
        return true;
    }
    return false;
}

So when $_SERVER['HTTPS'] not set, it checks the port and in our case it is 443 although it should be 80 so the function the returns TRUE.

**Comment by tomsommer** [comment]
Maybe you should look into why your server sets the port to 443 even though it's not running SSL. This is most likely not related to the bug?

We shouldn't manipulate $_SERVER['HTTPS'] because it will ruin sites that actually run SSL.

**Comment by VlooMan** [comment]
It's a shred hosting provider. We have notified them but cannot rely on waiting for the fix.

**Pull request merged**
